<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- This xacro file aims for adding the mobile platform to the robot-->

    <!-- ////////////////////////// BASE LINK //////////////////////////////-->
    <link name="base_link"/>
    
    <!-- ///////////////////////// PROPERTIES //////////////////////////////-->
    <xacro:property name="level_height" value="0.08"/>
    <xacro:property name="thickness" value="0.0025"/>

    <!-- /////////////////////////// LEVELS ///////////////////////////////-->
    <xacro:com_base level="0" parent="base_link" x="0" y="0"
        z="${level_height*0+ thickness*0}"/>
    <xacro:com_base level="1" parent="base_link" x="0" y="0" 
        z="${level_height*1 + thickness*1}"/>
    <xacro:com_base level="2" parent="base_link" x="0" y="0" 
        z="${level_height*2 + thickness*2}"/>
    <xacro:com_base level="3" parent="base_link" x="0" y="0" 
        z="${level_height*3 + thickness*3}"/>
    <xacro:half_base level="4" side="2" parent="base_link" x="0" y="0"
        z="${level_height*4 + thickness*4}"/>

    <!-- /////////////////////// LEVEL's SPACERS//////////////////////////-->
    <xacro:double_spacer_10x80 front="1" level="0" x="${0.15/2 - 0.0275}" 
            y="${0.21/2 - 0.010}" z="0"/>
    <xacro:double_spacer_10x80 front="2" level="0" x="${0.15/2 - 0.0275}" 
            y="${0.21/2 - 0.010}" z="0"/>
    <xacro:double_spacer_10x80 front="1" level="1" x="${0.15/2 - 0.0275}" 
            y="${0.21/2 - 0.010}" z="0"/>
    <xacro:double_spacer_10x80 front="2" level="1" x="${0.15/2 - 0.0275}" 
            y="${0.21/2 - 0.010}" z="0"/>
    <xacro:double_spacer_10x80 front="1" level="2" x="${-0.15/2 + 0.0275 + 0.006}" 
            y="${0.21/2 - 0.010}" z="0"/>
    <xacro:double_spacer_10x80 front="2" level="2" x="${0.15/2 - 0.0275}" 
            y="${0.21/2 - 0.010}" z="0"/>
    <xacro:double_spacer_10x80 front="2" level="3" x="${0.15/2 - 0.0275}" 
            y="${0.21/2 - 0.010}" z="0"/>
    <xacro:double_spacer_10x80 front="1" level="3" x="${-0.15/2 + 0.0075}" 
            y="${0.21/2 - 0.010}" z="0"/>
    
    <!-- //////////////////////// MOTORS DC ////////////////////////////-->
    <xacro:motor_dc front="1" side="1" x="-0.0025" y="${0.05718+0.036/2}" 
        z="-0.0225"/>
    <xacro:motor_dc front="1" side="2" x="-0.0025" y="${0.05718+0.036/2}"
        z="-0.0225"/>

    <!-- /////////////////////// CASTER WHEEL //////////////////////////-->

    <xacro:x4xmetric_spacer id="m4x17" element="caster" parent="base_l0_s2"
        offset_x="0.012" offset_y="0.015" x="-0.022" y="0" 
        z="${-0.001 - 0.017}"/>
    <xacro:caster_wheel parent="base_l0_s2" front="2" x="-0.022" y="0" 
        z="${-0.002 - 0.017}"/>

    <!-- //////////////// FIRST FLOOR COMPONENTS ///////////////////// -->
    <!-- Hex spacers for Battery Support -->
    <xacro:x6xmetric_spacer id="m3x10" element="bathol" parent="base_l0_s1"
        offset_x="${0.0855/2}" offset_y="${0.127/2}" x="0.005" y="0" 
        z="0.0025"/>
    
    <!-- Link Battery Support-->
    <link name="bat_platform">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi_2}"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/bathold_support.stl"
            scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="PureWhite"/>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 ${pi_2}"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/bathold_support.stl" 
            scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 ${pi_2}"/>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                iyy="0.001" iyz="0.0"
                izz="0.001"/>
    </inertial>
    </link>

    <!-- Joint Battery Support -->
    <joint name="bat_platform_joint" type="fixed">
        <parent link="base_l0_s1"/>
        <child link="bat_platform"/>
        <origin xyz="0.005 0 0.0125" rpy="0 0 0"/>
    </joint>

    <!-- Battery Stacks -->
    <xacro:stack_bat parent="bat_platform" num="1" x="0" y="-0.023" z="0"/>
    <xacro:stack_bat parent="bat_platform" num="2" x="0" y="${0.023+0.02}" 
        z="0"/>

    <!-- Hex spacers for Motor Driver-->
    <xacro:x4xmetric_spacer id="m3x10" element="driver" parent="base_l0_s2"
        offset_x="${0.03702/2}" offset_y="${-0.0368/2}" x="-0.023453" 
        y="0.031351" z="0.0025"/>

    <!-- Link Motor Driver-->
    <link name="driver_platform">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/driver.stl"
            scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="DriverRed"/>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/driver.stl" 
            scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                iyy="0.001" iyz="0.0"
                izz="0.001"/>
    </inertial>
    </link>

    <!-- Joint Motor Driver -->
    <joint name="driver_platform" type="fixed">
        <parent link="base_l0_s2"/>
        <child link="driver_platform"/>
        <origin xyz="-0.023453 0.031351 0.0125" rpy="0 0 0"/>
    </joint>

    <!-- Link Regulator Support-->
    <link name="reg_support">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 ${-pi_2}"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/regulator_sup.stl"
            scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="SoftBlack"/>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 ${-pi_2}"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/regulator_sup.stl" 
            scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 ${-pi_2}"/>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                iyy="0.001" iyz="0.0"
                izz="0.001"/>
    </inertial>
    </link>

    <!-- Joint Regulator Support -->
    <joint name="reg_support_joint" type="fixed">
        <parent link="base_l0_s2"/>
        <child link="reg_support"/>
        <origin xyz="-0.036 -0.0275 0.0025" rpy="0 0 0"/>
    </joint>

    <!-- Link Regulator Support-->
    <link name="regulator">
    <visual>
        <origin xyz="0 0 0" rpy="${pi_2} 0 ${-pi_2}"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/regulator.stl"
            scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="ArduinoBlue"/>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="${pi_2} 0 ${-pi_2}"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/regulator.stl" 
            scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>
    <inertial>
        <origin xyz="0 0 0" rpy="${pi_2} 0 ${-pi_2}"/>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                iyy="0.001" iyz="0.0"
                izz="0.001"/>
    </inertial>
    </link>

    <!-- Joint Regulator -->
    <joint name="reg_joint" type="fixed">
        <parent link="reg_support"/>
        <child link="regulator"/>
        <origin xyz="-0.0025 0 ${0.06/2}" rpy="0 0 0"/>
    </joint>


    <xacro:if value="${servo}">
        <xacro:servo_mounted parent="base_l1_s2" side="1" x="0.00275" y="0.0765"
            z="-0.026"/>
        <xacro:servo_mounted parent="base_l1_s2" side="2" x="0.00275" y="0.0765"
            z="-0.026"/>
    </xacro:if>

    <xacro:complete_lateral_wall id="servo" parent="base_l0_s1" side="1" 
        x="${-0.115/2}" y="${0.21/2 + 0.0005}" z="${0.082/2 + 0.0025/2}"
        level="0"/>

    <xacro:complete_lateral_wall id="servo" parent="base_l0_s1" side="2" 
        x="${-0.115/2}" y="${0.21/2 + 0.0005}" z="${0.082/2 + 0.0025/2}"
        level="0"/>

    <xacro:complete_front_wall id="batteries" parent="base_l0_s1" front="1" 
        x="${0.115/2}" z="${0.082/2 + 0.0025/2}" level="0"/>

    <xacro:complete_front_wall id="fdefault" parent="base_l0_s2" front="2" 
        x="${0.115/2}" z="${0.082/2 + 0.0025/2}" level="0"/>

    <!-- ///////////////// SECOND FLOOR COMPONENTS /////////////////////// -->
    <xacro:x4xmetric_spacer id="m3x10" element="esp_adapter" parent="base_l1_s1"
        offset_x="${0.0577/2}" offset_y="${0.0607/2}" x="0" y="0" z="-0.01"/>

    <!-- Link Esp32 Adapter -->
    <link name="esp32_adapter">
    <visual>
        <origin xyz="0 0 0" rpy="${pi} 0 0"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/esp32_adp.stl"
            scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="RaspberryGreen"/>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="${pi} 0 0"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/esp32_adp.stl" 
            scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>
    <inertial>
        <origin xyz="0 0 0" rpy="${pi} 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                iyy="0.001" iyz="0.0"
                izz="0.001"/>
    </inertial>
    </link>

    <!-- Joint Esp32 Adapter -->
    <joint name="esp32_adapter_joint" type="fixed">
        <parent link="base_l1_s1"/>
        <child link="esp32_adapter"/>
        <origin xyz="0 0 -0.01" rpy="0 0 0"/>
    </joint>

    <!-- Link Esp32 -->
    <link name="esp32">
    <visual>
        <origin xyz="0 0 0" rpy="${pi} 0 ${-pi_2}"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/esp32.stl"
            scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="SoftBlack"/>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="${pi} 0 ${-pi_2}"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/esp32.stl" 
            scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>
    <inertial>
        <origin xyz="0 0 0" rpy="${pi} 0 ${-pi_2}"/>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                iyy="0.001" iyz="0.0"
                izz="0.001"/>
    </inertial>
    </link>

    <!-- Joint Esp32 -->
    <joint name="esp32_joint" type="fixed">
        <parent link="esp32_adapter"/>
        <child link="esp32"/>
        <origin xyz="0.002 0 -0.01" rpy="0 0 0"/>
    </joint>

    <xacro:x3xmetric_spacer id="m3x10" element="lidar" parent="base_l1_s1" 
        offset_x="0.0234" offset_y="${0.03132/2}" x="-0.0575" y="0" z="0.0025"/>
    
    <!-- Link LD19 -->
    <link name="ld19">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/ld19.stl"
            scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="SoftBlack"/>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/ld19.stl" 
            scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                iyy="0.001" iyz="0.0"
                izz="0.001"/>
    </inertial>
    </link>

    <!-- Joint LD19 -->
    <joint name="ld19_joint" type="fixed">
        <parent link="base_l1_s1"/>
        <child link="ld19"/>
        <origin xyz="${-0.0575} -0.0035 0.0125" rpy="0 0 0"/>
    </joint>

    <!-- Link Lidar Serial -->
    <link name="lidar_serial">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/serial_ld.stl"
            scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="ArduinoBlue"/>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/serial_ld.stl" 
            scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                iyy="0.001" iyz="0.0"
                izz="0.001"/>
    </inertial>
    </link>

    <!-- Joint Lidar Serial -->
    <joint name="lidar_serial_joint" type="fixed">
        <parent link="base_l1_s2"/>
        <child link="lidar_serial"/>
        <origin xyz="-0.03 0.025 0.0025" rpy="0 0 0"/>
    </joint>

    <xacro:complete_lateral_wall id="llidar" parent="base_l1_s1" side="1" 
        x="${-0.115/2}" y="${0.21/2 + 0.0005}" z="${0.082/2 + 0.0025/2}"
        level="1"/>

    <xacro:complete_lateral_wall id="llidar" parent="base_l1_s1" side="2" 
        x="${-0.115/2}" y="${0.21/2 + 0.0005}" z="${0.082/2 + 0.0025/2}"
        level="1"/>

    <xacro:complete_front_wall id="flidar" parent="base_l1_s1" front="1" 
        x="${0.115/2}" z="${0.082/2 + 0.0025/2}" level="1"/>

    <xacro:complete_front_wall id="flidar" parent="base_l1_s2" front="2" 
        x="${0.115/2}" z="${0.082/2 + 0.0025/2}" level="1"/>

    <!-- ////////////////// THIRD FLOOR COMPONENTES ////////////////////// -->
    <xacro:if value="${rasp == 'rpi4'}">
        <xacro:speakers_mount parent="base_l2_s2" front="2" side="1" x="-0.0025" 
            y="0.0685" z= "0.0025"/>
        <xacro:speakers_mount parent="base_l2_s2" front="2" side="2" x="-0.0025"
            y="0.0685" z= "0.0025"/>

        <xacro:complete_lateral_wall id="speaker1" parent="base_l2_s1" side="1" 
            x="${-0.115/2}" y="${0.21/2 + 0.0005}" z="${0.082/2 + 0.0025/2}"
            level="2"/>

        <xacro:complete_lateral_wall id="speaker2" parent="base_l2_s1" side="2" 
            x="${-0.115/2}" y="${0.21/2 + 0.0005}" z="${0.082/2 + 0.0025/2}"
            level="2"/>

        <xacro:complete_front_wall id="fdefault" parent="base_l2_s2" front="2" 
            x="${0.115/2}" z="${0.082/2 + 0.0025/2}" level="2"/>
    </xacro:if>
    <!-- ////////////////// FOURTH FLOOR COMPONENTES ////////////////////// -->
    <xacro:x4xmetric_spacer id="m3x10" element="rpi5" parent="base_l3_s2"
        offset_x="${0.049/2}" offset_y="${0.058/2}" x="0" y="0.0435" z="0.0025"/>

    <!-- Link Rasberry Pi -->
    <link name="${rasp}">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 ${-pi_2}"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/${rasp}.stl"
            scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="RaspberryGreen"/>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 ${-pi_2}"/>
        <geometry>
        <mesh filename="package://orion_description/meshes/${rasp}.stl" 
            scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 ${-pi_2}"/>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                iyy="0.001" iyz="0.0"
                izz="0.001"/>
    </inertial>
    </link>

    <!-- Joint Rasberry Pi-->
    <joint name="${rasp}_joint" type="fixed">
        <parent link="base_l3_s2"/>
        <child link="${rasp}"/>
        <origin xyz="0 0.0335 0.0125" rpy="0 0 0"/>
    </joint>


    <xacro:complete_front_wall id="rpi" parent="base_l3_s2" front="2" 
        x="${0.115/2}" z="${0.082/2 + 0.0025/2}" level="3"/>
</robot>
