<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Macro for adding two symmetrical spacers -->
    <xacro:macro name="symmetrical_spacers" 
                params="name parent base_position offset_from_position mesh_file 
                        scale:=1.0 rpy:='0 0 0'">

        <!-- Left Spacer -->
        <link name="${name}_left">
        <visual>
            <geometry>
            <mesh filename="${mesh_file}" scale="${scale} ${scale} ${scale}"/>
            </geometry>
        </visual>
        </link>

        <joint name="${name}_left_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${name}_left"/>
        <origin xyz="${base_position[0] - offset_from_position} ${base_position[1]} ${base_position[2]}" 
                rpy="${rpy}"/>
        </joint>

        <!-- Right Spacer -->
        <link name="${name}_right">
        <visual>
            <geometry>
            <mesh filename="${mesh_file}" scale="${scale} ${scale} ${scale}"/>
            </geometry>
        </visual>
        </link>

        <joint name="${name}_right_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${name}_right"/>
        <origin xyz="${base_position[0] + offset_from_position} ${base_position[1]} ${base_position[2]}" 
                rpy="${rpy}"/>
        </joint>

    </xacro:macro>

    <!-- Macro for adding four symmetrical spacers -->
    <xacro:macro name="four_symmetrical_spacers" 
                params="name parent origin offset_x offset_y mesh_file 
                        scale:=1.0 rpy:='0 0 0'">

        <!-- Front-Left Spacer -->
        <link name="${name}_front_left">
        <visual>
            <geometry>
            <mesh filename="${mesh_file}" scale="${scale} ${scale} ${scale}"/>
            </geometry>
        </visual>
        </link>

        <joint name="${name}_front_left_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${name}_front_left"/>
        <origin xyz="${origin[0] - offset_x} ${origin[1] + offset_y} ${origin[2]}" rpy="${rpy}"/>
        </joint>

        <!-- Front-Right Spacer -->
        <link name="${name}_front_right">
        <visual>
            <geometry>
            <mesh filename="${mesh_file}" scale="${scale} ${scale} ${scale}"/>
            </geometry>
        </visual>
        </link>

        <joint name="${name}_front_right_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${name}_front_right"/>
        <origin xyz="${origin[0] + offset_x} ${origin[1] + offset_y} ${origin[2]}" rpy="${rpy}"/>
        </joint>

        <!-- Back-Left Spacer -->
        <link name="${name}_back_left">
        <visual>
            <geometry>
            <mesh filename="${mesh_file}" scale="${scale} ${scale} ${scale}"/>
            </geometry>
        </visual>
        </link>

        <joint name="${name}_back_left_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${name}_back_left"/>
        <origin xyz="${origin[0] - offset_x} ${origin[1] - offset_y} ${origin[2]}" rpy="${rpy}"/>
        </joint>

        <!-- Back-Right Spacer -->
        <link name="${name}_back_right">
        <visual>
            <geometry>
            <mesh filename="${mesh_file}" scale="${scale} ${scale} ${scale}"/>
            </geometry>
        </visual>
        </link>

        <joint name="${name}_back_right_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${name}_back_right"/>
        <origin xyz="${origin[0] + offset_x} ${origin[1] - offset_y} ${origin[2]}" rpy="${rpy}"/>
        </joint>

    </xacro:macro>

    <!--//////////////////// MATH AND NUMS MACROS ///////////////////////-->

    <xacro:property name="pi_2" value="${pi / 2}"/>
    <xacro:property name="pi_4" value="${pi / 4}"/>
    <xacro:property name="pi_6" value="${pi / 6}"/>
    <xacro:property name="pi_8" value="${pi / 8}"/>

    <!--///////////////////// 10 x 80 SPACERS MACROS ///////////////////////-->

    <!-- single custom spacer 10 x 80 mm -->
    <xacro:macro name="spacer_10x80" params="front side level x y z">
        <!-- Orientation properties -->
        <xacro:property name="muls" value="1"/>
        <xacro:if value="${side == 2}">
            <xacro:property name="muls" value="-1"/>
        </xacro:if>
        <xacro:property name="mulf" value="1"/>
        <xacro:if value="${front == 2}">
            <xacro:property name="mulf" value="-1"/>
        </xacro:if>
        <xacro:property name="gyro" value="${pi}"/>
        <xacro:if value="${side == 2 and front == 1}">
            <xacro:property name="gyro" value="${pi_2}"/>
        </xacro:if>
        <xacro:if value="${side == 1 and front == 2}">
            <xacro:property name="gyro" value="${3*pi_2}"/>
        </xacro:if>
        <xacro:if value="${side == 2 and front == 2}">
            <xacro:property name="gyro" value="0"/>
        </xacro:if>

        <!-- Link definition-->
        <link name="spacer_l${level}_${front}${side}">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${gyro}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/spacer_10x80.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="SoftBlack"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${gyro}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/spacer_10x80.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>

        <!-- Joint definition -->
        <joint name="spacer_l${level}_${front}${side}_joint" type="fixed">
            <parent link="base_l${level}_s${front}"/>
            <child link="spacer_l${level}_${front}${side}"/>
            <origin xyz="${x*mulf} ${y*muls} ${z+0.0025}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="double_spacer_10x80" params="front level x y z">
        <xacro:spacer_10x80 front="${front}" side="1" level="${level}" x="${x}"
            y="${y}" z="${z}"/>
        <xacro:spacer_10x80 front="${front}" side="2" level="${level}" x="${x}"
            y="${y}" z="${z}"/>
    </xacro:macro>
    
    <!--//////////////////// BASES AND LEVELS MACROS ///////////////////////-->
    <xacro:macro name="half_base" params="level side parent x y z">
        <xacro:property name="mul" value="1"/>
        <xacro:if value="${side == 2}">
            <xacro:property name="mul" value="-1"/>
        </xacro:if>

        <!-- Link -->
        <link name="base_l${level}_s${side}">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${mul*pi_2}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/half_platform.stl"
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="PureWhite"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${mul*pi_2}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/half_platform.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 ${mul*pi_2}"/>
            <mass value="0.1"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>

        <!-- Fixed Joint -->
        <joint name="base_l${level}_s${side}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="base_l${level}_s${side}"/>
            <origin xyz="${x + (mul*0.115/2)} ${y} ${z}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="com_base" params="level parent x y z">
        <xacro:half_base level="${level}" side="1" parent="base_link" x="${x}"
            y="${y}" z="${z}"/>
        <xacro:half_base level="${level}" side="2" parent="base_link" x="${x}"
            y="${y}" z="${z}"/>
    </xacro:macro>

    <xacro:macro name="generic_sphere" params="name parent x y z">
    
    <!-- Link -->
        <link name="${name}">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="0.005"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="0.005"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${x} ${y} ${z}"/>
            <mass value="0.1"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>

        <!-- Fixed Joint -->
        <joint name="${name}_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${name}"/>
        <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
        </joint>

    </xacro:macro>

    <!--  /////////////////// MOTOR DC MACROS ///////////////////////////////-->
    <!--  Motor DC Component Kit -->
    <xacro:macro name="motor_dc" params="front side x y z">
        <!-- Properties -->
        <xacro:property name="mulf" value="1"/>
        <xacro:if value="${front == 2}">
            <xacro:property name="mulf" value="-1"/>
        </xacro:if>
        <xacro:property name="muls" value="1"/>
        <xacro:property name="orin" value="0"/>
        <xacro:if value="${side == 2}">
            <xacro:property name="muls" value="-1"/>
            <xacro:property name="orin" value="${pi}"/>
        </xacro:if>
        <!-- Link motor mount definition-->
        <link name="motor_support_${front}${side}">
        <visual>
            <origin xyz="0 0 0" rpy="${pi} 0 ${orin}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/motor_mount.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="MetalGray"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi} 0 ${orin}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/motor_mount.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>
        <!-- Joint motor mount definition-->
        <joint name="motor_support_${front}${side}_joint" type="fixed">
            <parent link="base_l0_s${front}"/>
            <child link="motor_support_${front}${side}"/>
            <origin xyz="${x*mulf} ${y*muls} ${z+0.0025}" rpy="0 0 0"/>
        </joint>
        <!-- Link motor dc definition-->
        <link name="motor_dc_${front}${side}">
        <visual>
            <origin xyz="0 0 0" rpy="${-pi_2*muls} 0 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/motor_dc.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="MetalGray"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${-pi_2*muls} 0 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/motor_dc.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>
        <!-- Joint motor dc definition-->
        <joint name="motor_dc_${front}${side}_joint" type="fixed">
            <parent link="motor_support_${front}${side}"/>
            <child link="motor_dc_${front}${side}"/>
            <origin xyz="0 ${-0.05625*muls} 0" rpy="0 0 0"/>
        </joint>
        <!-- Link coupling definition-->
        <link name="coupling_${front}${side}">
        <visual>
            <origin xyz="0 0 0" rpy="${orin} 0 ${pi_6*muls}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/coupling.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="Brass"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${orin} 0 ${pi_6*muls}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/coupling.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>
        <!-- Joint coupling definition-->
        <joint name="coupling_${front}${side}_joint" type="continuous">
            <axis xyz="0.0 0.0 1.0"/>
            <parent link="motor_support_${front}${side}"/>
            <child link="coupling_${front}${side}"/>
            <origin xyz="0 ${(0.01120 + 0.000325)*muls} 0" rpy="${-pi_2*muls+orin} 0 0"/>
        </joint>
        <!-- LInk Ring  definition-->
        <link name="ring_${front}${side}">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${-pi_2*muls} 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/ring.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="ArduinoBlue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${-pi_2*muls} 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/ring.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>
        <!-- Joint ring definition-->
        <joint name="ring_${front}${side}_joint" type="fixed">
            <parent link="coupling_${front}${side}"/>
            <child link="ring_${front}${side}"/>
            <origin xyz="0 0 ${0.0068*muls}" rpy="0 0 0"/>
        </joint>
        <!-- Link neumatic definition-->
        <link name="neumatic_${front}${side}">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi_2*muls} 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/neumatic.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="SoftBlack"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi_2*muls} 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/neumatic.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>
        <!-- Joint neumatic definition-->
        <joint name="neumatic_${front}${side}_joint" type="fixed">
            <parent link="ring_${front}${side}"/>
            <child link="neumatic_${front}${side}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <!--////////////////////////// CASTER WHEEL ////////////////////////////-->

    <xacro:macro name="caster_wheel" params="parent front x y z">
        <!-- Link caster base definition-->
        <link name="caster_base_${front}">
        <visual>
            <origin xyz="0 0 0" rpy="${pi} 0 ${pi_2}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/caster_base.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="MetalGray"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi} 0 ${pi_2}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/caster_base.stl"
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>
        <!-- Joint caster base definition-->
        <joint name="caster_base_${front}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="caster_base_${front}"/>
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
        </joint>
        <!-- Link caster middle definition-->
        <link name="caster_middle_${front}">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${-pi_2}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/caster_middle.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="MetalGray"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${-pi_2}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/caster_middle.stl"
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>
        <!-- Joint caster middle definition-->
        <joint name="caster_middle_${front}_joint" type="continuous">
            <axis xyz="0.0 0.0 1.0"/>
            <parent link="caster_base_${front}"/>
            <child link="caster_middle_${front}"/>
            <origin xyz="0 0 -0.002" rpy="${pi} 0 0"/>
        </joint>
        <!-- Link caster wheel definition-->
        <link name="caster_wheel_${front}">
        <visual>
            <origin xyz="0 0 0" rpy="${pi_2} 0 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/caster_wheel.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="SoftBlack"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi_2} 0 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/caster_wheel.stl"
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>
        <!-- Joint caster wheel definition-->
        <joint name="caster_wheel_${front}_joint" type="continuous">
            <axis xyz="0.0 0.0 1.0"/>
            <parent link="caster_middle_${front}"/>
            <child link="caster_wheel_${front}"/>
            <origin xyz="-0.0108 0 0.0185" rpy="${pi/2} 0 0"/>
        </joint>
    </xacro:macro>

    <!-- ///////////////////// BATTERIES MACROS ////////////////////////////-->
    <!-- B18650 Macro-->
    <xacro:macro name="b18650" params="parent element num x y z">
        <xacro:property name="inv" value="1"/>
        <xacro:property name="rot" value="${pi_2}"/>
        <xacro:if value="${num == 2}">
            <xacro:property name="rot" value="${pi_2*3}"/>
            <xacro:property name="inv" value="-1"/>
        </xacro:if>
        <xacro:if value="${num == 3}">
            <xacro:property name="rot" value="${pi_2*5}"/>
        </xacro:if>
        <!-- Link -->
        <link name="${element}_${num}">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${rot} 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/b18650.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="DriverRed"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${rot} 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/b18650.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>

        <joint name="${element}_${num}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${element}_${num}"/>
            <origin xyz="${x*inv} ${y} ${z}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="bat_hold" params=" parent element num x y z">
        <!-- Link -->
        <link name="${element}_${num}">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${pi_2}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/batteryholderx3.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="SoftBlack"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${pi_2}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/batteryholderx3.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>

        <joint name="${element}_${num}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${element}_${num}"/>
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="stack_bat" params="parent num x y z">
        <xacro:property name="serie" value="0.009"/>
        <xacro:bat_hold parent="${parent}" element="bathold" num="${num}" 
            x="${x}" y="${y}" z="${z}"/>
        <xacro:b18650 parent="bathold_${num}" element="b18650_${num}" num="1" 
            x="${-0.065/2}" y="${serie}" z="0.01"/>
        <xacro:b18650 parent="bathold_${num}" element="b18650_${num}" num="2" 
            x="${-0.065/2}" y="${-serie}" z="0.01"/>
        <xacro:b18650 parent="bathold_${num}" element="b18650_${num}" num="3" 
            x="${-0.065/2}" y="${-serie*3}" z="0.01"/>
    </xacro:macro>

    <!-- //////////////////// SERVOS MACROS ///////////////////////////////-->

    <xacro:macro name="servo_mounted" params="parent side x y z">
        <!-- Servo Mount Link -->
        <xacro:property name="inv" value="1"/>
        <xacro:property name="flex" value="0"/>
        <xacro:if value="${side == 2}">
            <xacro:property name="inv" value="-1"/>
            <xacro:property name="flex" value="${pi}"/>
        </xacro:if>
        <link name="servo_support_${side}">
        <visual>
            <origin xyz="0 0 0" rpy="${-pi_2} 0 ${flex}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/servo_sup.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="SoftBlack"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${-pi_2} 0 ${flex}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/servo_sup.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>
        <!-- Servo Mount Joint -->
        <joint name="servo_support_${side}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="servo_support_${side}"/>
            <origin xyz="${x} ${y*inv} ${z}" rpy="0 0 0"/>
        </joint>
        <!-- Servo Link -->
        <link name="servo_${side}">
        <visual>
            <origin xyz="0 0 0" rpy="${-pi_2*inv} 0 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/mg996r.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="SoftBlack"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${-pi_2*inv} 0 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/mg996r.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>
        <!-- Servo Joint -->
        <joint name="servo_${side}_joint" type="fixed">
            <parent link="servo_support_${side}"/>
            <child link="servo_${side}"/>
            <origin xyz="0 ${-0.0216*inv} -0.01375" rpy="0 0 0"/>
        </joint>
        <!-- Servo Link -->
        <link name="servo_conn_${side}">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/servo_conn.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="MetalGray"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/servo_conn.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>
        <!-- Servo Joint -->
        <joint name="servo_conn${side}_joint" type="revolute">
            <axis xyz="0.0 0.0 1.0"/>
            <parent link="servo_${side}"/>
            <child link="servo_conn_${side}"/>
            <origin xyz="0.0115 ${0.0431*inv} 0" rpy="${-pi_2*inv} 0 0"/>
            <limit lower="${-pi_2}" upper="${pi_2}" effort="1.0" velocity="1.0"/>
            <dynamics damping="0.1" friction="0.01"/>
        </joint>
    </xacro:macro>
    <!--///////////////////// SPEAKERS MACROS ///////////////////////-->

    <!-- Speakers Macro -->
    <xacro:macro name="speakers_mount" params="parent front side x y z">
        <!--  Properties -->
        <xacro:property name="mulf" value="1"/>
        <xacro:property name="muls" value="1"/>
        <xacro:property name="inv" value="${pi}"/>
        <xacro:if value="${front == 2}">
            <xacro:property name="mulf" value="-1"/>
        </xacro:if>
        <xacro:if value="${side == 2}">
            <xacro:property name="muls" value="-1"/>
            <xacro:property name="inv" value="0"/>
        </xacro:if>
        <!-- Link speaker -->
        <link name="speaker_sup_${front}${side}">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${inv}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/speaker_sup.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="SoftBlack"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${inv}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/speaker_sup.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>
        <!-- Joint speaker support -->
        <joint name="speaker_sup_${front}${side}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="speaker_sup_${front}${side}"/>
            <origin xyz="${x*mulf} ${y*muls} ${z}" rpy="0 0 0"/>
        </joint>
        <!-- Link speaker support -->
        <link name="speaker_${front}${side}">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${inv}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/speaker.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="SoftBlack"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${inv}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/speaker.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>
        <!-- Joint speaker support -->
        <joint name="speaker_${front}${side}_joint" type="fixed">
            <parent link="speaker_sup_${front}${side}"/>
            <child link="speaker_${front}${side}"/>
            <origin xyz="0 ${0.0285*muls/2} 0" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <!-- ///////////////////////////// WALL MACROS //////////////////////// -->
    <xacro:macro name="complete_lateral_wall" 
            params="id parent side level x y z">
        <xacro:property name="muls" value="1"/>
        <xacro:property name="orx" value="${pi}"/>
        <xacro:if value="${side == 2}">
            <xacro:property name="muls" value="-1"/>
            <xacro:property name="orx" value="0"/>
        </xacro:if>
        <!-- Link -->
        <link name="wall${id}_${level}_${side}">
        <visual>
            <origin xyz="0 0 0" rpy="${orx} ${pi} 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/wall_${id}.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="TransparentBlack"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${orx} ${pi} 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/wall_${id}.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>

        <joint name="wall${id}_${level}_${side}_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="wall${id}_${level}_${side}"/>
        <origin xyz="${x} ${y*muls} ${z}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="complete_front_wall" 
            params="id parent front level x z">
        <xacro:property name="mulf" value="1"/>
        <xacro:property name="orz" value="0"/>
        <xacro:if value="${front == 2}">
            <xacro:property name="mulf" value="-1"/>
            <xacro:property name="orz" value="${pi}"/>
        </xacro:if>
        <!-- Link -->
        <link name="wall${id}_${level}_${front}">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${pi_2 + orz}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/wall_${id}.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="TransparentBlack"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${pi_2 + orz}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/wall_${id}.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>

        <joint name="wall${id}_${level}_${front}_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="wall${id}_${level}_${front}"/>
        <origin xyz="${x*mulf} 0 ${z}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <!-- /////////////////////////// Generic Metric Spacer /////////////////-->
    <xacro:macro name="metric_spacer"
            params="id parent element front side x y z">
        
        <!-- Link Spacer -->
        <link name="${id}_${element}_${front}${side}">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/spacer_${id}.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="Brass"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/spacer_${id}.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0 " rpy="0 0 0"/>
            <xacro:if value="${id == 'm4x17'}">
                <mass value="0.0024"/>
                <inertia ixx="8.5251996963501e-08" ixy="0" ixz="0"
                        iyy="8.648216387229408e-08" iyz="0"
                        izz="1.333016690879308e-08"/>
            </xacro:if>
            <xacro:if value="${id == 'm3x10'}">
                <mass value="0.0012"/>
                <inertia ixx="1.2825999244689955e-08" ixy="0" ixz="0"
                        iyy="1.3441082699086494e-08" iyz="0"
                        izz="6.66508345439654e-09"/>
            </xacro:if>
        </inertial>
        </link>
        <!-- Joint Spacer -->
        <joint name="${id}_${element}_${front}${side}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${id}_${element}_${front}${side}"/>
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <!-- 2 symetric hex spacers by considering offset -->
    <xacro:macro name="x2xmetric_spacer" 
                params="id element parent offset_y x y z">
        <xacro:metric_spacer id="${id}" parent="${parent}" element="${element}" 
            front="" side="r" x="${x}" y="${y - offset_y}" z="${z}"/>
        <xacro:metric_spacer id="${id}" parent="${parent}" element="${element}" 
            front="" side="l" x="${x}" y="${y + offset_y}" z="${z}"/>
    </xacro:macro>

    <!-- 3  hex spacers by considering triangle -->
    <xacro:macro name="x3xmetric_spacer" 
                params="id element parent offset_x offset_y x y z">
        <xacro:metric_spacer id="${id}" parent="${parent}" element="${element}" 
            front="f" side="l" x="${x + offset_x}" y="${y - offset_y}" z="${z}"/>
        <xacro:metric_spacer id="${id}" parent="${parent}" element="${element}" 
            front="r" side="l" x="${x - offset_x}" y="${y - offset_y}" z="${z}"/>
        <xacro:metric_spacer id="${id}" parent="${parent}" element="${element}" 
            front="" side="r" x="${x}" y="${y + offset_y}" z="${z}"/>
    </xacro:macro>

    <!-- 4  hex spacers by considering mirror offset -->
    <xacro:macro name="x4xmetric_spacer" 
                params="id element parent offset_x offset_y x y z">
        <xacro:metric_spacer id="${id}" parent="${parent}" element="${element}" 
            front="f" side="r" x="${x + offset_x}" y="${y - offset_y}" z="${z}"/>
        <xacro:metric_spacer id="${id}" parent="${parent}" element="${element}" 
            front="f" side="l" x="${x + offset_x}" y="${y + offset_y}" z="${z}"/>
        <xacro:metric_spacer id="${id}" parent="${parent}" element="${element}" 
            front="r" side="r" x="${x - offset_x}" y="${y + offset_y}" z="${z}"/>
        <xacro:metric_spacer id="${id}" parent="${parent}" element="${element}" 
            front="r" side="l" x="${x - offset_x}" y="${y - offset_y}" z="${z}"/>
    </xacro:macro>

    <!-- 6  hex spacers by considering mirror offset and middles-->
    <xacro:macro name="x6xmetric_spacer" 
                params="id element parent offset_x offset_y x y z">
        <xacro:metric_spacer id="${id}" parent="${parent}" element="${element}" 
            front="f" side="r" x="${x + offset_x}" y="${y - offset_y}" z="${z}"/>
        <xacro:metric_spacer id="${id}" parent="${parent}" element="${element}" 
            front="f" side="l" x="${x + offset_x}" y="${y + offset_y}" z="${z}"/>
        <xacro:metric_spacer id="${id}" parent="${parent}" element="${element}" 
            front="r" side="r" x="${x - offset_x}" y="${y + offset_y}" z="${z}"/>
        <xacro:metric_spacer id="${id}" parent="${parent}" element="${element}" 
            front="r" side="l" x="${x - offset_x}" y="${y - offset_y}" z="${z}"/>
        <xacro:metric_spacer id="${id}" parent="${parent}" element="${element}" 
            front="f" side="" x="${x + offset_x}" y="0" z="${z}"/>
        <xacro:metric_spacer id="${id}" parent="${parent}" element="${element}" 
            front="r" side="" x="${x - offset_x}" y="0" z="${z}"/>
    </xacro:macro>
</robot>
