<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Macro for adding two symmetrical spacers -->
    <xacro:macro name="symmetrical_spacers" 
                params="name parent base_position offset_from_position mesh_file 
                        scale:=1.0 rpy:='0 0 0'">

        <!-- Left Spacer -->
        <link name="${name}_left">
        <visual>
            <geometry>
            <mesh filename="${mesh_file}" scale="${scale} ${scale} ${scale}"/>
            </geometry>
        </visual>
        </link>

        <joint name="${name}_left_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${name}_left"/>
        <origin xyz="${base_position[0] - offset_from_position} ${base_position[1]} ${base_position[2]}" 
                rpy="${rpy}"/>
        </joint>

        <!-- Right Spacer -->
        <link name="${name}_right">
        <visual>
            <geometry>
            <mesh filename="${mesh_file}" scale="${scale} ${scale} ${scale}"/>
            </geometry>
        </visual>
        </link>

        <joint name="${name}_right_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${name}_right"/>
        <origin xyz="${base_position[0] + offset_from_position} ${base_position[1]} ${base_position[2]}" 
                rpy="${rpy}"/>
        </joint>

    </xacro:macro>

    <!-- Macro for adding four symmetrical spacers -->
    <xacro:macro name="four_symmetrical_spacers" 
                params="name parent origin offset_x offset_y mesh_file 
                        scale:=1.0 rpy:='0 0 0'">

        <!-- Front-Left Spacer -->
        <link name="${name}_front_left">
        <visual>
            <geometry>
            <mesh filename="${mesh_file}" scale="${scale} ${scale} ${scale}"/>
            </geometry>
        </visual>
        </link>

        <joint name="${name}_front_left_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${name}_front_left"/>
        <origin xyz="${origin[0] - offset_x} ${origin[1] + offset_y} ${origin[2]}" rpy="${rpy}"/>
        </joint>

        <!-- Front-Right Spacer -->
        <link name="${name}_front_right">
        <visual>
            <geometry>
            <mesh filename="${mesh_file}" scale="${scale} ${scale} ${scale}"/>
            </geometry>
        </visual>
        </link>

        <joint name="${name}_front_right_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${name}_front_right"/>
        <origin xyz="${origin[0] + offset_x} ${origin[1] + offset_y} ${origin[2]}" rpy="${rpy}"/>
        </joint>

        <!-- Back-Left Spacer -->
        <link name="${name}_back_left">
        <visual>
            <geometry>
            <mesh filename="${mesh_file}" scale="${scale} ${scale} ${scale}"/>
            </geometry>
        </visual>
        </link>

        <joint name="${name}_back_left_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${name}_back_left"/>
        <origin xyz="${origin[0] - offset_x} ${origin[1] - offset_y} ${origin[2]}" rpy="${rpy}"/>
        </joint>

        <!-- Back-Right Spacer -->
        <link name="${name}_back_right">
        <visual>
            <geometry>
            <mesh filename="${mesh_file}" scale="${scale} ${scale} ${scale}"/>
            </geometry>
        </visual>
        </link>

        <joint name="${name}_back_right_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${name}_back_right"/>
        <origin xyz="${origin[0] + offset_x} ${origin[1] - offset_y} ${origin[2]}" rpy="${rpy}"/>
        </joint>

    </xacro:macro>

    <!--//////////////////// MATH AND NUMS MACROS ///////////////////////-->

    <xacro:property name="pi_2" value="${pi / 2}"/>
    <xacro:property name="pi_4" value="${pi / 4}"/>
    <xacro:property name="pi_6" value="${pi / 6}"/>
    <xacro:property name="pi_8" value="${pi / 8}"/>

    <!--///////////////////// 10 x 80 SPACERS MACROS ///////////////////////-->

    <!-- single custom spacer 10 x 80 mm -->
    <xacro:macro name="spacer_10x80" params="front side level x y z">
        <xacro:property name="muls" value="1"/>
        <xacro:if value="${side == 2}">
            <xacro:property name="muls" value="-1"/>
        </xacro:if>
        <xacro:property name="mulf" value="1"/>
        <xacro:if value="${side == 2}">
            <xacro:property name="mulf" value="-1"/>
        </xacro:if>

        <!-- Link -->
        <link name="spacer_l${level}_${front}${side}">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${muls*pi}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/spacer_10x80.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${muls*pi}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/spacer_10x80.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>

        <joint name="spacer_l${level}_${front}${side}_joint" type="fixed">
            <parent link="base_l${level}_s${side}"/>
            <child link="spacer_l${level}_${front}${side}"/>
            <origin xyz="${x*mulf} ${y*muls} ${z+0.0025}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>
    
    <!--//////////////////// BASES AND LEVELS MACROS ///////////////////////-->
    <xacro:macro name="half_base" params="level side parent x y z">
        <xacro:property name="mul" value="1"/>
        <xacro:if value="${side == 2}">
            <xacro:property name="mul" value="-1"/>
        </xacro:if>

        <!-- Link -->
        <link name="base_l${level}_s${side}">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${mul*pi_2}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/half_platform.stl"
                scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${mul*pi_2}"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/half_platform.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 ${mul*pi_2}"/>
            <mass value="0.1"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>

        <!-- Fixed Joint -->
        <joint name="base_l${level}_s${side}_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="base_l${level}_s${side}"/>
        <origin xyz="${x + (mul*0.115/2)} ${y} ${z}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="com_base" params="level parent x y z">
        <xacro:half_base level="${level}" side="1" parent="base_link" x="${x}"
            y="${y}" z="${z}"/>
        <xacro:half_base level="${level}" side="2" parent="base_link" x="${x}"
            y="${y}" z="${z}"/>
    </xacro:macro>

    <xacro:macro name="generic_sphere" params="name parent x y z">
    
    <!-- Link -->
        <link name="${name}">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="0.005"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="0.005"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${x} ${y} ${z}"/>
            <mass value="0.1"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>

        <!-- Fixed Joint -->
        <joint name="${name}_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${name}"/>
        <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
        </joint>

    </xacro:macro>

    <!--///////////////////// M3 x 10 SPACERS MACROS ///////////////////////-->

    <!-- Hex spacer M3 x 10 macro -->
    <xacro:macro name="spacer_m3x10" 
            params="name parent element front side x y z">
        
        <!-- Link -->
        <link name="${name}_${element}_${front}${side}">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/spacer_m3x10.stl" 
                scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://orion_description/meshes/spacer_m3x10.stl" 
                scale="1 1 1"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.0053"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001"/>
        </inertial>
        </link>

        <joint name="${name}_${element}_${front}${side}_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${name}"/>
        <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <!-- 2 symetric hex spacers by considering y axis -->
    <xacro:macro name="2xspacer_m3x10" 
                params="name element parent offset_y x y z">
        <xacro:spacer_m3x10 name="${name}" parent="${parent}" element="${element}" 
            front="" side="r" x="${x}" y="${y - offset_y}" z="${z}"/>
        <xacro:spacer_m3x10 name="${name}" parent="${parent}" element="${element}" 
            front="" side="l" x="${x}" y="${y + offset_y}" z="${z}"/>
    </xacro:macro>

    <!-- 4 symetric hex spacers by considering x/y axis -->
    <xacro:macro name="4xspacer_m3x10" 
                params="name element parent offset_x offset_y x y z">
        <xacro:spacer_m3x10 name="${name}" parent="${parent}" element="${element}" 
            front="f" side="r" x="${x + offset_x}" y="${y - offset_y}" z="${z}"/>
        <xacro:spacer_m3x10 name="${name}" parent="${parent}" element="${element}" 
            front="f" side="l" x="${x + offset_x}" y="${y + offset_y}" z="${z}"/>
        <xacro:spacer_m3x10 name="${name}" parent="${parent}" element="${element}" 
            front="r" side="r" x="${x - offset_x}" y="${y + offset_y}" z="${z}"/>
        <xacro:spacer_m3x10 name="${name}" parent="${parent}" element="${element}" 
            front="r" side="l" x="${x - offset_x}" y="${y - offset_y}" z="${z}"/>
    </xacro:macro>


</robot>
