mobile_base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

    # Joint specifications
    left_wheel_names: ["coupling_11_joint"]
    right_wheel_names: ["coupling_12_joint"]

    # Wheel properties
    wheel_separation: 0.183
    wheel_radius: 0.033675

    # Additional wheel properties
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # Publiscation of data and variance
    publish_rate: 30.0
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]
    
    # Timeout for commands
    cmd_vel_timeout: 0.5
    
    # Frames to consider
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true

    # Control considerations
    open_loop: false

    # Command considerations
    publish_limited_velocity: true
    use_stamped_vel: false

    # Linear velocity elements
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.max_velocity: 2.791666667  # m/s
    linear.x.min_velocity: -2.791666667 # m/s
    linear.x.max_acceleration: 0.5 # m/s²
    linear.x.min_acceleration: -0.5 # m/s²
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    # Angular velocity elements
    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.max_velocity: 2.791666667  # m/s
    angular.z.min_velocity: -2.791666667 # m/s
    angular.z.max_acceleration: 1.0  # m/s²
    angular.z.min_acceleration: -1.0 # m/s²
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN